# Generated by Django 4.2.11 on 2024-12-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Name of the service', max_length=255)),
                ('video_length', models.PositiveIntegerField(help_text='Length of the video in seconds')),
                ('hooks_numbers', models.PositiveIntegerField(help_text='Number of hooks in the video')),
                ('call_to_action_number', models.PositiveIntegerField(help_text='Number of call-to-actions')),
                ('voice_over', models.BooleanField(default=False, help_text='Does the video include voice-over?')),
                ('face_appearing', models.BooleanField(default=False, help_text='Does the video include face appearing?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Users.creator')),
            ],
        ),
    ]
