# Generated by Django 4.2.11 on 2024-12-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='call_to_action_number',
        ),
        migrations.AddField(
            model_name='service',
            name='call_to_action',
            field=models.CharField(default='1-2', help_text='Number of calls to action (e.g., 1-2)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Snapchat', 'Snapchat'), ('Tiktok', 'Tiktok'), ('Youtube', 'Youtube')], default='insta', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2.3, help_text='Price in Syrian pounds', max_digits=10),
            preserve_default=False,
        ),
    ]
