# Generated by Django 4.2.11 on 2024-12-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_service_call_to_action_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='avg_completion_rate',
            field=models.PositiveIntegerField(default=0, help_text='Average completion rate in percentage'),
        ),
        migrations.AddField(
            model_name='creator',
            name='avg_response_speed',
            field=models.CharField(blank=True, help_text="Average response speed (e.g., '2 hours')", max_length=50),
        ),
        migrations.AddField(
            model_name='creator',
            name='clients_number',
            field=models.PositiveIntegerField(default=0, help_text='Number of clients'),
        ),
        migrations.AddField(
            model_name='creator',
            name='facebook_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creator',
            name='instagram_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creator',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Last seen timestamp'),
        ),
        migrations.AddField(
            model_name='creator',
            name='register_date',
            field=models.DateField(default='2024-12-27', help_text='Date of registration'),
        ),
        migrations.AddField(
            model_name='creator',
            name='reviews',
            field=models.PositiveIntegerField(default=0, help_text='Number of reviews'),
        ),
        migrations.AddField(
            model_name='creator',
            name='services_number',
            field=models.PositiveIntegerField(default=0, help_text='Number of services'),
        ),
        migrations.AddField(
            model_name='creator',
            name='snapchat_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creator',
            name='tiktok_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creator',
            name='youtube_followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
