# Generated by Django 4.2.11 on 2024-12-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_creator_avg_completion_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='industry',
        ),
        migrations.AddField(
            model_name='brand',
            name='about_me',
            field=models.TextField(blank=True, help_text='Description of the brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='avg_order_time',
            field=models.PositiveIntegerField(default=0, help_text='Average order completion time in percentage'),
        ),
        migrations.AddField(
            model_name='brand',
            name='avg_response_speed',
            field=models.CharField(blank=True, help_text="Average response speed (e.g., '2 hours')", max_length=50),
        ),
        migrations.AddField(
            model_name='brand',
            name='facebook_followers',
            field=models.PositiveIntegerField(default=0, help_text='Number of followers on Facebook'),
        ),
        migrations.AddField(
            model_name='brand',
            name='instagram_followers',
            field=models.PositiveIntegerField(default=0, help_text='Number of followers on Instagram'),
        ),
        migrations.AddField(
            model_name='brand',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Last seen timestamp'),
        ),
        migrations.AddField(
            model_name='brand',
            name='order_number',
            field=models.PositiveIntegerField(default=0, help_text='Number of orders made'),
        ),
        migrations.AddField(
            model_name='brand',
            name='register_date',
            field=models.DateField(default='2024-12-27', help_text='Date of registration'),
        ),
        migrations.AddField(
            model_name='brand',
            name='snapchat_followers',
            field=models.PositiveIntegerField(default=0, help_text='Number of followers on Snapchat'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tiktok_followers',
            field=models.PositiveIntegerField(default=0, help_text='Number of followers on TikTok'),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='youtube_followers',
            field=models.PositiveIntegerField(default=0, help_text='Number of followers on YouTube'),
        ),
    ]
