# Generated by Django 4.2.11 on 2024-12-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_brand_company_name_remove_brand_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='reviews',
        ),
    ]
