# Generated by Django 4.2.11 on 2024-12-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_creator_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video for this service', null=True, upload_to='service_videos/'),
        ),
    ]
