# Generated by Django 5.1.4 on 2024-12-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default='sb', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='phone_number',
            field=models.CharField(default='0939949117', max_length=20),
            preserve_default=False,
        ),
    ]
