# Generated by Django 5.1.4 on 2025-01-02 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_brand_brand_name_brand_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Upload a video for this service', null=True, upload_to='service_videos/')),
                ('description', models.TextField(blank=True, help_text='Optional description for the video')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Users.service')),
            ],
        ),
    ]
