# Generated by Django 5.1.4 on 2025-01-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_remove_service_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='video_links',
        ),
        migrations.AddField(
            model_name='creator',
            name='average_rating',
            field=models.FloatField(default=0.0, help_text='Average rating for the creator.'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography of the creator.', null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='profile_pic',
            field=models.URLField(blank=True, help_text='URL of the profile picture.', null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='register_date',
            field=models.DateField(auto_now_add=True, help_text='Date of registration'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating score (e.g., 1-5)')),
                ('review', models.TextField(blank=True, help_text='Optional review text', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Users.brand')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Users.creator')),
                ('service_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Users.servicevideo')),
            ],
        ),
    ]
