# Generated by Django 5.1.4 on 2025-01-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_remove_creator_rating_remove_creator_video_links_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='creator',
            old_name='user_id',
            new_name='user',
        ),
    ]
