# Generated by Django 5.1.4 on 2025-01-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_rename_user_id_brand_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
