# Generated by Django 5.1.4 on 2025-01-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_alter_cartitem_service_alter_order_service_and_more'),
        ('Users', '0014_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='servicevideo',
            name='service',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceVideo',
        ),
    ]
