# Generated by Django 5.1.7 on 2025-03-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_remove_creator_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of registration'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of registration'),
        ),
    ]
