# Generated by Django 5.1.7 on 2025-04-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_alter_brand_register_date_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'email'], name='Users_user_user_ty_27e7be_idx'),
        ),
    ]
