# Generated by Django 5.1.4 on 2025-01-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='call_to_action',
        ),
        migrations.AddField(
            model_name='service',
            name='call_to_action_number',
            field=models.PositiveIntegerField(default=1, help_text='Number of call-to-actions'),
            preserve_default=False,
        ),
    ]
