# Generated by Django 5.1.4 on 2025-01-24 16:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevideo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
