# Generated by Django 5.1.4 on 2025-01-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_servicevideo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='content',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Snapchat', 'Snapchat'), ('Tiktok', 'Tiktok'), ('Youtube', 'Youtube')], default='Instagram', max_length=10),
        ),
        migrations.AlterField(
            model_name='content',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
