# Generated by Django 5.1.4 on 2025-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_remove_content_average_rating_content_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_portfolio_item',
            field=models.BooleanField(default=True),
        ),
    ]
