# Generated by Django 5.1.7 on 2025-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_content_is_portfolio_item'),
        ('Users', '0018_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['service', 'ugc_type', 'platform'], name='Services_co_service_6de6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['creator', 'platform'], name='Services_se_creator_84f29e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevideo',
            index=models.Index(fields=['service'], name='Services_se_service_a0152e_idx'),
        ),
    ]
