# Generated by Django 4.2.11 on 2024-12-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Chat', '0004_alter_message_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='Users.brand'),
        ),
    ]
