# Generated by Django 5.1.4 on 2025-01-23 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0014_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(help_text='Rating score (e.g., 1-5)')),
                ('review', models.TextField(blank=True, help_text='Optional review text', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Users.brand')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Users.creator')),
            ],
        ),
    ]
