# Generated by Django 5.1.4 on 2025-01-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reviews', '0001_initial'),
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Services.servicevideo'),
        ),
    ]
