# Generated by Django 5.1.4 on 2025-01-24 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_alter_review_rating'),
        ('Services', '0001_initial'),
        ('Users', '0016_remove_creator_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Users.brand'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Users.creator'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Services.servicevideo'),
        ),
    ]
