# Generated by Django 5.1.4 on 2025-03-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0004_alter_review_brand_alter_review_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(default='It is fine', help_text='Mandatory review text'),
            preserve_default=False,
        ),
    ]
