# Generated by Django 4.2.11 on 2024-12-14 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.brand'),
        ),
        migrations.AddField(
            model_name='order',
            name='brief',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Orders.brief'),
        ),
        migrations.AddField(
            model_name='brief',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.brand'),
        ),
        migrations.AddField(
            model_name='brief',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.creator'),
        ),
    ]
