# Generated by Django 4.2.11 on 2024-12-19 22:09

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


# class Migration(migrations.Migration):

#     dependencies = [
#         ('Orders', '0003_brief_created_at'),
#     ]

#     operations = [
       
#         migrations.AddField(
#             model_name='payment',
#             name='order',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Orders.order'),
#             preserve_default=False,
#         ),
        
#     ]

# Generated by Django on YYYY-MM-DD HH:MM

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_brief_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('payment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=models.CASCADE, related_name='payment', to='Orders.Order')),
                ('user_id', models.OneToOneField(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
