# Generated by Django 4.2.11 on 2024-12-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_remove_payment_order_id_payment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brief',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Orders.brief'),
        ),
    ]
