# Generated by Django 4.2.11 on 2024-12-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Orders', '0005_alter_order_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='Users.brand'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='Users.creator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Users.brand'),
        ),
    ]
