# Generated by Django 5.1.4 on 2025-01-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_rename_total_price_order_amount_remove_order_brief_and_more'),
        ('Users', '0012_remove_creator_rating_remove_creator_video_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='brand',
            field=models.ForeignKey(default='25fc68c2a0cc43d6aa046d434b2a48e1', on_delete=django.db.models.deletion.CASCADE, to='Users.brand'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('CREDITCARD', 'Credit Card')], default='PAYPAL', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Orders.order'),
        ),
    ]
