# Generated by Django 5.1.4 on 2025-01-19 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_alter_payment_options_remove_payment_payment_date_and_more'),
        ('Users', '0012_remove_creator_rating_remove_creator_video_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='Users.creator'),
        ),
    ]
