# Generated by Django 5.1.4 on 2025-02-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_rename_amount_order_total_price_remove_order_service_and_more'),
        ('Services', '0006_content_is_portfolio_item'),
        ('Users', '0016_remove_creator_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='Users.brand'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Orders.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Services.service'),
        ),
    ]
