# Generated by Django 5.1.4 on 2025-02-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_alter_cart_brand_alter_cartitem_cart_and_more'),
        ('Users', '0016_remove_creator_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(default='defb1c623813436597f9475f9f55d4a6', on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to='Users.creator'),
        ),
    ]
