# Generated by Django 5.1.4 on 2025-02-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_remove_order_total_price_order_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
            preserve_default=False,
        ),
    ]
