# Generated by Django 5.1.4 on 2025-02-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0015_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='date',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_method',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('CREDITCARD', 'Credit Card')], max_length=50),
        ),
    ]
