# Generated by Django 5.1.4 on 2025-03-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0016_add_date_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='withdrawal',
            name='account_details',
            field=models.CharField(max_length=1024),
        ),
    ]
