# Generated by Django 5.1.4 on 2025-03-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0017_alter_account_details'),
        ('Services', '0006_content_is_portfolio_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='created_at',
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'service')},
        ),
    ]
