# Generated by Django 5.1.4 on 2025-03-08 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0020_alter_fee_id_alter_promocode_id'),
        ('Services', '0006_content_is_portfolio_item'),
    ]

    operations = [

        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.fee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Services.service'),
        ),
    ]
