# Generated by Django 5.1.4 on 2025-03-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0022_remove_order_promo_code_remove_transaction_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
    ]
