# Generated by Django 5.1.4 on 2025-03-09 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0024_order_promo_code'),
        ('Services', '0006_content_is_portfolio_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Services.service'),
        ),
    ]
