# Generated by Django 5.1.4 on 2025-03-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0025_transaction_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
