# Generated by Django 5.1.4 on 2025-03-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0026_orderitem_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fee',
        ),
    ]
