# Generated by Django 5.1.4 on 2025-03-11 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0027_remove_order_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.fee'),
        ),
    ]
