# Generated by Django 5.1.4 on 2025-03-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0028_order_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
