# Generated by Django 5.1.4 on 2025-03-13 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0029_delete_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='price',
        ),
    ]
