# Generated by Django 5.1.4 on 2025-03-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0030_rename_amount_payment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
    ]
