# Generated by Django 5.1.4 on 2025-03-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0031_remove_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('service', 'Service Income'), ('withdraw', 'Paypal Withdraw')], max_length=50),
        ),
    ]
