# Generated by Django 5.1.4 on 2025-03-15 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0034_alter_withdrawal_state'),
        ('Users', '0016_remove_creator_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='Users.brand'),
        ),
    ]
