# Generated by Django 5.1.4 on 2025-03-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0036_payment_card_cvc_payment_card_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
