# Generated by Django 5.1.4 on 2025-03-22 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0037_balance_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.fee'),
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.promocode'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], default='fixed', max_length=10),
        ),
    ]
