# Generated by Django 5.1.4 on 2025-03-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0038_cart_fee_cart_promo_code_promocode_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_cvc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
    ]
