# Generated by Django 5.1.4 on 2025-03-22 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0039_remove_payment_card_cvc_remove_payment_card_expiry_and_more'),
        ('Users', '0016_remove_creator_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to='Users.creator'),
        ),
    ]
