# Generated by Django 5.1.7 on 2025-04-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0042_alter_cartitem_quantity'),
        ('Services', '0007_content_services_co_service_6de6fd_idx_and_more'),
        ('Users', '0018_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['brand', 'creator'], name='Orders_orde_brand_i_ae2d01_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'service'], name='Orders_orde_order_i_78e3e8_idx'),
        ),
    ]
